version: '3.3'

services:
  rabbitmq:
    image: "rabbitmq:latest"
    container_name: rabbit
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
